version: '3.8'
services:
  vuln-app:
    build: ./vuln-app
    ports:
      - "5000:5000"
    volumes:
      - ./vuln-app:/app
    command: >
      sh -c "
        if [ -f instance/vuln_shop.db ]; then
          rm instance/vuln_shop.db && echo 'Database removed.';
        fi;
        python init_db.py &&
        flask run
      "

  vuln-graphql:
    build: ./vuln-graphql
    ports:
      - "4000:4000"
    volumes:
      - ./vuln-graphql:/usr/src/app
      - /usr/src/app/node_modules
